### ISSUE TITLE
Improper handling of  "analyzer" in mapping

### ISSUE THREAD

**Issue by joeatbayes** [taskrabbit/elasticsearch-dump#110]
The following is one of the fields in the mapping returned from the source server.   This fails when attempting to copy the mappings using the --type=mapping with a error indicating that text_analyzer is recognized.  
"myfieldname": { "type": "string", "analyzer": "text_analyzer" }
}

The original definition for "text_analyzer"  was made in a settings command posted with the index creation for the remote index.  Unfortunately those settings are not returned as part of the _mapping from the remote server.   I worked around this by deleting the , "analyzer": "text_analyzer"  portion and creating the index manually but need cleaner handling.   

A better handling may be to remove the "analyzer" spec if you get an error trying to create that mapping in the target server.

I was copying from a elastic search version 1.3.1 to 1.7.1 but the same error occured when tested copying into version 1.4.3

**Comment by evantahler** [comment]
Since I don't there is a way to extract the original command used to create the analyzer from an index, I think the right thing to is to actually throw an error, as the mappings really wont be correct.   We could add an option, `--skipAnalyzers` for the mapping import/exports.  

Thoughts?

**Comment by joeatbayes** [comment]
I like the --skipanalyzers option.

**Comment by evantahler** [comment]
Cool.  We'll leave this issue open.
Pull requests welcome!

**Comment by giocaputo** [comment]
I think that the problem is with a file for analyzer...

elasticdump --input=http://{ip_address_from}/searchproduct/ --output=./data/production_searchproduct_analyzer.json  --type=analyzer

elasticdump --input=./data/production_searchproduct_analyzer.json --output=http://{ip_address_to}/searchproduct/ --type=analyzer

i have error...
Wed, 13 Apr 2016 07:54:44 GMT | starting dump
Wed, 13 Apr 2016 07:54:44 GMT | got 1 objects from source file (offset: 0)
Wed, 13 Apr 2016 07:55:14 GMT | Error Emitted => failed to parse json (message: "Unexpected token o") - source:


This work correctly
elasticdump --input=http://{ip_address_from}/searchproduct/ --output=http://{ip_address_to}/searchproduct/ --type=analyzer

**Comment by evantahler** [comment]
@giocaputo can you please share a file that doesn't work (and a mapping from ES directly that does)?  without a test case, this won't get fixed

**Comment by giocaputo** [comment]
@evantahler "{\"searchproduct\":{\"settings\":{\"index\":{\"creation_date\":\"1460463367823\",\"analysis\":{\"analyzer\":{\"case_insensitive_sort\":{\"filter\":[\"lowercase\"],\"type\":\"custom\",\"tokenizer\":\"keyword\"},\"path_tokenizer\":{\"type\":\"custom\",\"tokenizer\":\"path_tokenizer\"}},\"tokenizer\":{\"path_tokenizer\":{\"type\":\"path_hierarchy\",\"delimiter\":\"/\"}}},\"number_of_shards\":\"5\",\"number_of_replicas\":\"1\",\"uuid\":\"euYkOcJTSD6mwba20NarLA\",\"version\":{\"created\":\"2020099\"}}}}}"

There is a " character at start and end of file. The \ escape... but also without it there is a problem

**Comment by dprski33** [comment]
> but mappers and data is not encoded like this and they work fine.

Having this same issue which means that analyzer dumps to files cannot be restored to a working index.

**Comment by dprski33** [comment]
@ferronrsmith why did you close this?
