### ISSUE TITLE
Error in target index when using the --bulk command option and alias

### ISSUE THREAD

**Issue by joeatbayes** [taskrabbit/elasticsearch-dump#111]
Source indexes may have a alias called "news"   but the physical index is something like news-018181 so you can create new physical indexes and activate them by shifting the aliases.   When copying using your tool I wanted to copy from the alias "news" to the local index "news" without worrying about the actual number of the active news index.     When using the command without --bulk it works correctly and places data in the correct index "news"   but when using the same command with the --bulk option it creates a new index "news-018181"  the same as the source index name and places the data in it.  The proper behavior would be to support the mapping the same way in both scenarios.

EG:  The following two indexes should produce the same output regardless when the source index /news is a physical index or an alias.

elasticdump  --input=http://server1.xyz.com:9700/news --output=http://127.0.0.1:9700/news --type=data

elasticdump  --bulk --input=http://server1.xyz.com:9700/news --output=http://127.0.0.1:9700/news --type=data

**Comment by evantahler** [comment]
We are agreed that the behavior without `--bulk` is clear and makes sense.  However, I think what `--bulk` is doing in this case is actually correct, since ES returns each object appended with data about the index it came from (under the alias) when using the bulk API.  

I think the behavior you want is "formally" something like `bulkAndMove`, since you want to change the content of the document fetched, and change the index.  

Thoughts?

**Comment by joeatbayes** [comment]
Agreed but it should be clear in the docs that the target index name will be ignored when using the bulk.    I like the bulkandmove option.

**Comment by evantahler** [comment]
Note added to readme: https://github.com/taskrabbit/elasticsearch-dump/commit/6739ef9a2f7e4da0aad978a0f6af641ef237b8e3

Pull requests welcome for the `bulkAndMove` feature!
