### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Calpicow** [taskrabbit/elasticsearch-dump#125]
Running a dump with

`./elasticdump --input=http://host1/index1 --output=https://host2/index2 --bulk --bulk-use-output-index-name`

After a while (about 100k documents in), I start getting a lot of 
`(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.`

Until it stops with
`RangeError: Maximum call stack size exceeded`

**Comment by evantahler** [comment]
Can you reproduce this error on a dataset you can share publicly?

**Comment by evantahler** [comment]
Closing due to lack of response

**Comment by initialcontext** [comment]
I'm on Ubuntu 16.04 using NPM 1.3.10 and node 0.10.25. Elasticdump version 2.4.2.

I hit this same issue trying to migrate a large (~30GB unreplicated) index from one cluster to another today, happened multiple times about 30 minutes into the job. I was using a `--limit` of 10k instead of default 100. Set at 1000 now, restarted from scratch, and the job hasn't died yet but not sure if I'm just not deep into the index enough yet.

I'm not much of a NodeJS expert but some poking around the internets (and the warning in the log lines before the job dies) suggest [this](https://github.com/taskrabbit/elasticsearch-dump/search?utf8=%E2%9C%93&q=nextTick) could be the issue? Anyone else hit this since the ticket was closed out?

Slightly redacted command I'm running now:
```
elasticdump --limit=1000 --maxSockets=4 --type=data --input=http://source_cluster:9200/my_index --output=http://destination_cluster:9200/my_index
```

Thanks again!

**Comment by evantahler** [comment]
Can you share a stack trace or something more detailed about the error?  This is not enough information to help you

**Comment by initialcontext** [comment]
Hey thanks for the quick reply. Can't share too much there, `elasticdump` was puttering along logging each batch of data, then a bunch of these warning logs:
```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
```

and then finally crashing with no error trace but only this line:
```
RangeError: Maximum call stack size exceeded
```

My new job runs aren't done yet so I don't want to speak too soon, but they've already progressed much further than the old ones so I feel confident they will complete without trouble. Only difference is `--limit=1000` on these new runs instead of `--limit=10000`. But my host had memory and CPU to spare it didn't OOM or anything when the jobs would fail this way with the larger limit setting.

I don't know much about NodeJS but I suspect a callback that fires per-record read is abusing `nextTick` and with the large `--limit` the recursion gets too deep and exceeds the limit on call stack size? I'd have to dig into it further to furnish better details but, _good news for those who encounter this issue: lowering the `--limit` a bit closer to the default size seems to have worked, regardless._

Thanks again, I'll post here if these jobs end up failing or I hit further complications. If things go well from here I'll try to circle back to this and maybe try to reproduce/patch it on the larger limit setting, and shoot you a PR. Thanks again for the nice tool.

**Comment by initialcontext** [comment]
Haven't dug much further into the underlying issue/fix yet but I can confirm my indices copied successfully using the lower `--limit` setting, so that works in a pinch if someone else hits the same issue. Thanks again

**Comment by evantahler** [comment]
Happy you got it to work!

We can remove the `nextTick`, but that was only a warning.  I think it is more likley that the volume of data you were ingesting per batch was more than could fit in RAM of the process.

**Comment by evantahler** [comment]
Oh, only the `file` transport uses `nextTick`.  Transfering from one server to another won't touch that code.

**Comment by initialcontext** [comment]
Yeah, had one more small hiccup with some queries timing out on a big index but I think i just needed to set `--scrollTime` higher than default for those, otherwise great thanks again for the help. The one odd thing about all this (and I see in the CLI the fellow who opened the issue also) is that we both got lots of `nextTick` warnings then a recursive call stack size error that killed the job, but both our jobs were HTTP => HTTP (no file source/dest on in or out).

From what I could tell at the time the memory situation on the process and the box seemed to have room to spare? That isn't a very scientific sample though, I'll certain try to reproduce with better detail when I get the chance. Thanks again!

**Comment by evantahler** [comment]
A full stack trace would really help here :D

**Comment by initialcontext** [comment]
Totally understandable I'll see what I can do there :)

**Comment by kitsaravana** [comment]
Thu, 21 Jun 2018 11:55:41 GMT | got 10000 objects from source elasticsearch (offset: 59100000)
Thu, 21 Jun 2018 11:55:41 GMT | sent 10000 objects to destination file, wrote 10000

<--- Last few GCs --->

[1588:0x22da5a0]  4261239 ms: Mark-sweep 1378.3 (1456.5) -> 1378.3 (1456.5) MB, 1228.9 / 0.0 ms  allocation fai                                                         lure GC in old space requested
[1588:0x22da5a0]  4262263 ms: Mark-sweep 1378.3 (1456.5) -> 1378.3 (1424.0) MB, 1023.9 / 0.0 ms  last resort GC                                                          in old space requested
[1588:0x22da5a0]  4263273 ms: Mark-sweep 1378.3 (1424.0) -> 1378.3 (1424.0) MB, 1009.8 / 0.0 ms  last resort GC                                                          in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2f049a9a55e9 <JSObject>
    1: stringSlice(aka stringSlice) [buffer.js:580] [bytecode=0xacf9f2fb659 offset=11](this=0x10a53b8822d1 <und                                                         efined>,buf=0x2d8868f2d119 <Uint8Array map = 0x26d07dbd9e91>,encoding=0x10a53b8822d1 <undefined>,start=0,end=21                                                         17976)
    2: toString [buffer.js:~634] [pc=0x141573d511df](this=0x2d8868f2d119 <Uint8Array map = 0x26d07dbd9e91>,enco                                                         ding=0x10a53b8822d1 <undefined>,start=0x10a53b8822d1 <unde...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8d04bc [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Factory::NewStringFromOneByte(v8::internal::Vector<unsigned char const>, v8::internal::Preten                                                         ureFlag) [node]
 7: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [no                                                         de]
 8: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [node]
 9: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*)                                                          [node]
10: 0x8eb9b2 [node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
12: 0xb17d2c [node]
13: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
14: 0x141573c042fd
