### ISSUE TITLE
elasticdump using basic auth fails

### ISSUE THREAD

**Issue by jorgenb** [taskrabbit/elasticsearch-dump#174]
I am using `elasticdump --input=https://user:secret@service/index --output=index.json --type=data` to try and export an index protected by Basic Auth living in a two node Elasticsearch 2.2.0 cluster made available via a NGINX frontend.

It fails with a 403 response from NGINX. I'm seeing this in my access.log:

```
10.0.1.10 - user [10/Mar/2016:20:37:35 +0100] "GET /index/_settings HTTP/1.1" 200 179 "-" "-"
10.0.1.10 - user [10/Mar/2016:20:37:35 +0100] "GET /index/_search?search_type=scan&scroll=10m&size=20 HTTP/1.1" 200 351 "-" "-"
10.0.1.10 - user [10/Mar/2016:20:37:35 +0100] "GET /_search/scroll?scroll=10m HTTP/1.1" 403 66 "-" "-"
```

The last `GET` request from the client seems to be off.

**Comment by evantahler** [comment]
I'm not able to reproduce this.  Testing with basic auth works fine...

```
111.222.333.444 - taskrabbit [11/Mar/2016:12:45:18 -0500] "GET /events_staging__2015_06/_settings HTTP/1.1" 200 196 "-" "-" "-" 0.002
111.222.333.444 - taskrabbit [11/Mar/2016:12:45:18 -0500] "GET /events_staging__2015_06/_search?search_type=scan&scroll=10m&size=100 HTTP/1.1" 200 211 "-" "-" "-" 0.010
111.222.333.444 - taskrabbit [11/Mar/2016:12:45:18 -0500] "GET /_search/scroll?scroll=10m HTTP/1.1" 200 557908 "-" "-" "-" 0.248
111.222.333.444 - taskrabbit [11/Mar/2016:12:45:18 -0500] "GET /_search/scroll?scroll=10m HTTP/1.1" 200 546652 "-" "-" "-" 0.242
111.222.333.444 - taskrabbit [11/Mar/2016:12:45:19 -0500] "GET /_search/scroll?scroll=10m HTTP/1.1" 200 533411 "-" "-" "-" 0.245
111.222.333.444 - taskrabbit [11/Mar/2016:12:45:19 -0500] "GET /_search/scroll?scroll=10m HTTP/1.1" 200 336367 "-" "-" "-" 0.162
```

**Comment by evantahler** [comment]
If you can provide any more details, let us know

**Comment by jorgenb** [comment]
Thanks for responding. Problem was caused by an incorrectly configured nginx frontend.

**Comment by sunnyfrancis** [comment]
Hi,
I am trying to run command like below:

elasticdump --input=http://**user1**:password1@test-es-host.com/**test***_sourceIndex1 --output=<outputpath1> --type=mapping && elasticdump --input=http://**user1**:password1@test-es-host.com/**test***_sourceIndex1 --output=<outputpath> --type=data

and getting error user1 is not authorized to GET /_search/scroll
because of  security reasons user1 has access to get scroll or perform different operations with index starting with test* only, how can we fix this issue? as the user cannot be given rights to perform scroll on the whole ES cluster.

**Comment by evantahler** [comment]
How are you controlling the auth rules for your cluster?  Scroll permissions are required.  If you can't grant them on a per-index basis, you *will* need to grant them on the whole cluster to allow this tool to work

**Comment by sunnyfrancis** [comment]
Thanks for your response @evantahler 
One question, so if provide scroll permission per index will this work?

**Comment by evantahler** [comment]
no idea... again, *how* are you managing permissions?  Elasticsearch doesn't offer this kind of access control normally, so it's not something we can test for.   Give it a shot and let us know!

**Comment by sunnyfrancis** [comment]
Hi @evantahler this would work but we cannot manage index level permissions. I think it would be good if the module is performing _search/scroll on the index rather than the whole cluster index, though it would be accessing just specific index but that would be a security issue as there can be different applications running on the same cluster.
Let me know if this can be fixed.

**Comment by evantahler** [comment]
That's not something that I'm going to dedicate any time to personally. Again, you haven't answered *how* you are doing this access control, as access control is not something that is built into Elasticsearch.   As far as I know, access to the `scoll` API in Elasticsearch is at the cluster level.

That said, if you are willing so submit a pull request, I would be happy to take a look!
