### ISSUE TITLE
Support field renaming

### ISSUE THREAD

**Issue by JD557** [taskrabbit/elasticsearch-dump#183]
Hello,

I'm currently reindexing an elasticsearch 1.x database to make it ready for 2.x. This means that I must rename all fields with dots in their name.

It would be nice to have some sort of rename option. I'm not sure how to expose this (maybe `--map-from=data.x,data.google.\com --map-to=data.y,data.google_com`).

I need this ASAP, so I'm OK with sending a PR. I would need some pointers though (I only need to make some changes to `setMapping` and `setData`, right?).

Also, do you have some better ideas to expose this option?

**Comment by evantahler** [comment]
Hi!

While the use-case you describe makes sense, I'm wondering if perhaps it doesn't belong in the tool.  I'm coming from the point-of-view that we probably already have too many options/flags... and I want to keep the tool as simple as it can be.  

If you dump the index out to a file, you can find/replace the field names, and then re-import the index.  While that ads a manual step (and you cant go directly from index1->index2), it should allow you to do what you *today* without any changes.  Do you need to be able to do the replacement on the fly without the manual step?

If you do want to submit a PR, I think you would need to modify both the `elasticsearch` and `file` transports, as folks would expect that option to work in both places.  I would suggest making your modifications in the "getter" so that the fields are already renamed before passing them on to the writers. For `elasticsearch`, you would need to itterate though `hits` somewhere around here: https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L463
For `file`, you would need to check each `elem` returned by the read buffer and do the rename here-ish https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/file.js#L49

I would suggest making a shared helper which could be invoked by all the transports

**Comment by JD557** [comment]
>If you dump the index out to a file, you can find/replace the field names, and then re-import the index. While that ads a manual step (and you cant go directly from index1->index2), it should allow you to do what you today without any changes. Do you need to be able to do the replacement on the fly without the manual step?

You are right, this seems like a better approach. While it should be slower, I think adding this option would add unnecessary complexity to this project (I don't see any way of setting mapping rules as an option that is both simple and powerful).

I will close this issue and add the manual step to my reindex script. Thanks for your help.

**Comment by evantahler** [comment]
cool.  good luck!
