### ISSUE TITLE
Can you release rpm?

### ISSUE THREAD

**Issue by vananiev** [taskrabbit/elasticsearch-dump#201]
Today I use official nmp to build rpm-package for elasticdump (it easyer to deploy for me, and maybe for other peoples). Here is SPEC file, you can use (I already used it, it tasted):
```
Name:       elasticdump
Version:    2.0.1
Release:    1%{?dist}
License:    Apache License 2.0
Summary:    Elasticdump util

URL:        https://github.com/taskrabbit/elasticsearch-dump

BuildRequires:  nodejs >= 1.0.0
Requires:       nodejs >= 1.0.0

%description

%install
rm -rf %{buildroot}
npm_prefix="%{buildroot}/usr"
mkdir -p $npm_prefix
npm -g -q --production --prefix="$npm_prefix" install %{name}

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
/usr/bin/*
/usr/lib/node_modules/%{name}


%changelog
```
You can use `make rpm` for build rpm, if create Makefile with this content
```
RPMBUILD=/usr/bin/rpmbuild
all: rpm

rpm: $(RPMBUILD)
        $(RPMBUILD) --define "_topdir %(pwd)/rpmbuild" -bb rpmbuild/SPECS/elasticdump.spec

%:
        @:
```

**Comment by evantahler** [comment]
I do not think this is a good idea.  I certainly understand that you may have a specific use-case where deployment via RPM is easier, but I don't that we should "officially" manage it. 

You already are required to install node.js on your system (and the current stable version in Debain/ubuntu is not compatible with this tool, as it is version 0.10.x).  Since you have node.js, you have npm as well.  I would rather use the node-specific package manager, as it is guaranteed to be cross-platform (supporting windows, osx, and debian).    

Why manage distributions on more than package manager when we are already distributed on the most compatible one?  

I'll leave this issue open for others to comment...

**Comment by vananiev** [comment]
rpm (and other packages for others) more comfortable then installing without internet connect. tar in this case can't be used because updates become complicated. node.js version > 1.0 are in yum and other [repos](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora) and can be downloaded by `yumdownloader `and installed on server without internel connection.

**Comment by evantahler** [comment]
Assuming you already have node installed, since all of elasticdump's dependancies are plain JS files (no compiled binaries) you can certainly ZIP up the project and run it from an extracted volume, if that's your worry. 

If you want alternative ways to install node.js, this is not the right place for that conversation.
