### ISSUE TITLE
AWS signed request for root query - Improvement suggestion

### ISSUE THREAD

**Issue by maximeloizeau** [taskrabbit/elasticsearch-dump#283]
Hello,

I am quite new to AWS elasticsearch and I just secured it behind a policy that requires to be authenticated (key + secret).
For my setup, even the root is protected so elasticdump is not able to request for the version number.

My suggestion is to sign [this request](https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L40) but I am not sure if other setups would be affected by a change like this.

I was about to submit a pull request but I would like to know about this first if anyone has a feedback.

Thanks

**Comment by evantahler** [comment]
Makes sense! There are other signed requests in this project to use as an example (look for `aws4signer `).
  
Please correct via pull request!

**Comment by jhovell** [comment]
Thinking this may prevent using AWS auth with older versions of ES. 

I am trying to read data from an old (1.5) cluster and getting the debug message
```
Wed, 29 Mar 2017 00:53:28 GMT [debug] | cannot discover elasticsearch input major version, assuming: 5
```
...

and then immediately an error about failing to search, I'm guessing because elasticdump thinks the cluster is version 5.
```
Wed, 29 Mar 2017 00:53:28 GMT | Error Emitted => {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[EmPZOhp1TI2V2kmtYDZvHw][logstash-2017.02.28][0]: RemoteTransportException[[Golden Archer][inet[/x.x.x.x:y]][indices:data/read/search[phase/query+fetch]]]; nested: SearchParseException[[logstash-2017.02.28][0]: query[ConstantScore(*:*)],from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"stored_fields\":[\"*\"],\"_source\":true,\"size\":100}]]]; nested: SearchParseException[[logstash-2017.02.28][0]: query[ConstantScore(*:*)],from[-1],size[-1]: Parse Failure [No parser for element [stored_fields]]]; }]","status":400}
Wed, 29 Mar 2017 00:53:28 GMT | Total Writes: 0
Wed, 29 Mar 2017 00:53:28 GMT | dump ended with error (get phase) => Error: {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[EmPZOhp1TI2V2kmtYDZvHw][logstash-2017.02.28][0]: RemoteTransportException[[Golden Archer][inet[/x.x.x.x:y]][indices:data/read/search[phase/query+fetch]]]; nested: SearchParseException[[logstash-2017.02.28][0]: query[ConstantScore(*:*)],from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"stored_fields\":[\"*\"],\"_source\":true,\"size\":100}]]]; nested: SearchParseException[[logstash-2017.02.28][0]: query[ConstantScore(*:*)],from[-1],size[-1]: Parse Failure [No parser for element [stored_fields]]]; }]","status":400}
```

@evantahler you're still interested in a PR for this? I could see some sense in modernizing the AWS v4 signing altogether - AWS has gotten better Node support for doing this recently - See some Node examples in this blog post:
https://aws.amazon.com/blogs/aws/amazon-elasticsearch-service-support-for-es-5-1/
... though that may not be compatible with the rest of this library, I'd have to look.

Though in general it would also be nice to get away from the 'awsauth' dependency and use ALL standard AWS methods of auth (env variables, ec2 metadata profile, ecs task host (would be very helpful with the docker build for this project), etc...) and not be stuck with having to write credentials to disk or leave them on the command line

**Comment by evantahler** [comment]
I would love a PR for this!

**Comment by jhovell** [comment]
@evantahler I created a PR. I had trouble getting one or two tests to pass locally even before my changes, so hopefully it was a setup issue on my end and tests will all pass.

https://github.com/taskrabbit/elasticsearch-dump/pull/304

**Comment by atorok** [comment]
Looks like the functionality is there, and PR was merged, should close the issue.
