### ISSUE TITLE
Do not support routing

### ISSUE THREAD

**Issue by doubleuhy** [taskrabbit/elasticsearch-dump#400]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
- Elasticsearch version
- Node.js version
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem

**Comment by ferronrsmith** [comment]
It's very important that you take the time to formulate your questions so that we can aid you in a timely manner. 

Yes routing is supported. If the data that is dumped contains routing metdata **elasticsearch-dump** will make use of that field.

Additionally you can use the `---params` to add the routing param to the destination index.

**NB: This will route all documents to the particular route**

There is also the `--tranform` if you want to add deterministic routing..
