### ISSUE TITLE
Issue with migration in BOOLEAN data type

### ISSUE THREAD

**Issue by amitbsconcept** [taskrabbit/elasticsearch-dump#408]
Hi, 

When i was trying to do the data migration between 2 of my servers - it gave me following error / issue
`Current token (VALUE_NUMBER_INT) not of boolean type`
How can we resolve this following issue?

- ElasticDump version - 3.3.7
- Elasticsearch version (source 5.5.1 / target 6.1.3)
- Node.js version (8.10.0)
- Full command - elasticdump --input=http://source:9200/mentions --output=http://destination:8200/mentions --type=data
- A data set

```json
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1840,
    "max_score": 1,
    "hits": [
      {
        "_index": "mentions",
        "_type": "mention",
        "_id": "AWJn8Eu-cn3fSRv0O7Ra",
        "_score": 1,
        "_source": {
          "client_id": "2069",
          **"is_reply": 0,
          "is_retweet": 0,
          "is_mention": 1,**
          "mention_user_id": 570927672,
          "mention_user_name": "News by  Murali Kumar",
          "mention_screen_name": "muralikumarje",
          "profile_image_url": "http://pbs.twimg.com/profile_images/967046792222142464/w0k77Sr6_normal.jpg",
          "parent_mention_id": "",
          "platform": "twitter",
          "mention_id": "978641761647042561",
          "mention_type": "tweet",
          "mention_title": "",
          "mention": "RT @JustNifty: Bajaj Finance: Weeks of consolidation over - Add to investments. https://t.co/TKrBq3Vsf3",
          "source": """<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>""",
          "mentioned_on": "2018-03-27 20:05:52",
          "language": "en",
          "media": [
            {
              "media_url": "http://pbs.twimg.com/media/DZS80G-VoAAzQVk.jpg",
              "media_url_https": "https://pbs.twimg.com/media/DZS80G-VoAAzQVk.jpg",
              "display_url": "https://t.co/TKrBq3Vsf3",
              "expanded_url": "https://twitter.com/JustNifty/status/978615285354659840/photo/1",
              "media_type": "photo"
            },
            {
              "media_url": "",
              "media_url_https": "",
              "display_url": "https://t.co/TKrBq3Vsf3",
              "expanded_url": "",
              "media_type": "photo",
              "url": "",
              "type": ""
            }
          ]
      }
    ]
  }
}
````

**Comment by ferronrsmith** [comment]
It's always important to read the change-logs before moving to a new major version.

> **Coercion of boolean fields**
Previously, Elasticsearch recognized the strings true, false, on, off, yes, no, 0, 1 as booleans. Elasticsearch 6.0 recognizes only the strings true and false as booleans and will throw an error otherwise. For backwards compatibility purposes, during the 6.x series the previous coercion rules will continue to work on pre-6.0 indices. This means that you do not need to change affected existing mappings immediately. However, it is not possible to create new indices from existing index templates that violate the strict boolean coercion rules. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_mappings_changes.html
