### ISSUE TITLE
elastic dump fails if indice having huge data

### ISSUE THREAD

**Issue by manuchitturi** [taskrabbit/elasticsearch-dump#450]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 3.3.14
- Elasticsearch version 2.x
- NODE_JS_MAJOR_VERSION=8
-PYTHON_VERSION=3.5.5
-PYTHON_PIP_VERSION=10.0.1
-NODE_OPTIONS=--max_old_space_size=536870912
 elasticdump
    - --limit=500
    - --input=https://estrialdata001A.mgmt.tv3cloud.net:9200/spark_app_log-2018.06.17
    - --output=$
    - --httpAuthFile=/tmp/tmpkj9uyvdg
    - --type=data

Error:
"events.js:183\n      throw er; // Unhandled 'error' event\n      ^\n\
      \nError: write ENOBUFS\n    at _errnoException (util.js:992:11)\n    at Socket._writeGeneric\
      \ (net.js:764:25)\n    at Socket._writev (net.js:778:8)\n    at doWrite (_stream_writable.js:395:12)\n\
      \    at clearBuffer (_stream_writable.js:501:5)\n    at onwrite (_stream_writable.js:449:7)\n\
      \    at WriteWrap.afterWrite [as oncomplete] (net.js:876:12)\n"

**Comment by ferronrsmith** [comment]
This is really a memory issue and not exactly an elastic-dump issue. There is so much that back-pressuring can do, but eventually if there is too much data it will fail. My advice, use searchBody to query subsets.

**Comment by manuchitturi** [comment]
I am new to elastic . Please help me
My requirement is to dump the complete data from existing 2.x server.For indices with less volume of data, everything works fine, but when i tried to dump an indice of size 25 gb , it fails.
Please help what property i need to set (Are talking about ram? if yes, currently machine using 16gb ram).

NODE_OPTIONS=--max_old_space_size=536870912

**Comment by ferronrsmith** [comment]
Try writing to a file, but I remember dumping a large index (10GB) and it failed due to same memory issues. Back-pressure works for node, but when the output is piped. The post-processor might not have a large enough buffer to handle the output. 

I am thinking of implementing a segment/split feature, to split after X MB/GB or N records.

**Comment by manuchitturi** [comment]
We are dumping records into gzip file and we are splitting files  for every 1 million records.

**Comment by tholu** [comment]
@manuchitturi How are you doing the split? Currently running into the same issue, did you solve it?

**Comment by Sheldon1999** [comment]
Hi I am trying to dump a index of size about 10 GB using the following node.js code.

```
const exportData = () => {
    return new Promise((resolve, reject) => {
      const authOptions = `${USERNAME}:${PASSWORD}`;
      const authUrl = `http://${authOptions}@${HOST}/${INDEX}`;
  
      const dataDump = spawn(ELASTICDUMP_PATH, ['--input=' + authUrl, '--output=$']);
      const writeStream = fs.createWriteStream(DATA_FILE);
  
      dataDump.stdout.pipe(writeStream);
  
      dataDump.on('close', (code) => {
        if (code !== 0) {
          reject(`Data dump process exited with code ${code}`);
        } else {
          resolve();
        }
      });
      dataDump.on('error', (err) => reject(`Data dump error: ${err}`));
    });
  };
```

the file size has got above 17 GB, and it's sill running. I am not getting what's the problem here?

**Comment by ferronrsmith** [comment]
An Elasticsearch index is compressed data. 10 GB might be 25 GB uncompressed. There are various issues here.

1. Memory (machine or node limitation hence the max_old_space_size, which is only useful if you're reading faster than writing)
2. ?Node string length limitation. If you're dumping too much string data at once.
3. FS limitation. Since the file has to be buffered and written to, sometimes appending might be a long operation, hence the file-size param to limit the overall output size of each file (splitting the files.)


i.e. It's not a one size fits all scenario
