### ISSUE TITLE
Feature request: Allow TLS X509 client authentication

### ISSUE THREAD

**Issue by juanluisvaladas** [taskrabbit/elasticsearch-dump#491]
Hi, I think it would be useful to be able to configure the options for TLS using flags, for my use case, I run elasticsearch behind searchguard [1] and use TLS X509 authentication.

I don't really care about how it's configure, but if I were to implement this I would copy the curl flags, so if the requests library has:

var options = {
    url: 'https://api.some-server.com/',
    cert: fs.readFileSync(certFile),
    key: fs.readFileSync(keyFile),
    passphrase: password,
    ca: fs.readFileSync(caFile)
};

certFile would match the flag --cert <certfile>
password would be --cert <certfile:password>
caFile would be: --cacert
keyFile would be: --key

1- https://github.com/floragunncom/search-guard

**Comment by ferronrsmith** [comment]
feel free to submit a PR.

**Comment by morningspace** [comment]
Hey, come across here when I was looking for a tool to migrate data between ES clusters... It looks great, but just I need cert and key as I'm using SSL. I submitted a PR just now, and it's a draft version just to check whether it's on the way. Feel free to comment. @ferronrsmith FYI

BTW: I was trying to understand what's the major difference between this tool and the native reindex supported by ES itself since they both use scroll search. So far, my understanding is that, apart from more inputs & outputs are supported, e.g. dump to a file, it also can skip records when offset is specified, while all these are not part of ES reindex feature. Correct me if any. Thanks!
