### ISSUE TITLE
how to dump mongodb json to ES ?

### ISSUE THREAD

**Issue by maverickpravin** [taskrabbit/elasticsearch-dump#523]
- ElasticDump version - 4.6.0
- Elasticsearch version - 6.6
- Node.js version 10.13

I want to ask, how can i dump mongodb json dataset to ES. I couldn't  find any relevant document yet.
Thank you for this simple but amazing tool.

**Comment by ferronrsmith** [comment]
It's not supported out the box, but it shouldn't be hard to do.

You can build a custom transport and then pass it in has an `--inputTransport`
It would look something like this.

https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/_template.js

```javascript
class mongo {
  constructor (parent, options) {
    this.options = options
    this.parent = parent
  }

  // accept callback
  // return (error, arr) where arr is an array of objects
  get (limit, offset, callback) {
    const error = null
    const data = []
    // transform the data before passing it to elasticdump
    // format is shown below.
    callback(error, data)
  }
}

module.exports = {
  mongo
}
```

That way you can stream the data from mognodb to elasticsearch.

The other option is to dump the data then use the `tranform` fix the data so that is can be ingested.

The expected format looks like :

```json
{"_index":"users","_type":"seeds","_id":"67785","_score":1,"_source":{"id":"67785", "name":"abcd", "hobby":"abcde"}}
```

> **NB: Format needs to be JSONL**
