### ISSUE TITLE
[BUG] Performance tuning documentation

### ISSUE THREAD

**Issue by ChaosCA** [taskrabbit/elasticsearch-dump#587]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.7.5 (latest docker container)
- Elasticsearch version: 7.0.1

**Describe the bug**
I am using elasticdump to backup a large index of about 19million entries (honestly not even that large on elasticsearch standards) and it takes a pretty long time (~2 hours). I would like to know how I can improve the performance of elasticdump, maybe parallelize it using --offset? 

There's no examples for doing something like this in the documentation and I think it would be worth adding.

**Comment by ferronrsmith** [comment]
It already does parallelization. I really don't know the record size etc, it's hard to give advice without context, but concurrent read/wite is already on by default. Please check the documentation.

1. increase limit
1. offset is a bad idea since the offset records will need to be stored in memory. i.e Elasticsearch dropped support for offset in scroll
1. Too many concurrent reads can have negative effects since ES has a read pool, too much request can actually cause bottle-necks/rejections.



Benchmarking your data is the best way to find the right settings.

**Comment by ChaosCA** [comment]
These three instructions are very vague, I still think these questions is relevant to address in documentation.

**Comment by ferronrsmith** [comment]
All the documentation in the world won’t help optimise performance. If your have an understanding of elasticsearch and node.js then doing optimisations in pretty straightforward. 

Each case is different and what might work for you might not work for someone else, hence the reason for benchmarking. Understanding your systems limitations is very important.

1. Research Es optimisation
1. Research node optimisation 

You can also search previous issues for tips that others have used to increase throughput.

**Comment by ferronrsmith** [comment]
If you want to submit a PR for review that’s fine
