### ISSUE TITLE
Import/Export documents with version

### ISSUE THREAD

**Issue by kgrygoryan-clgx** [taskrabbit/elasticsearch-dump#653]
I'm trying to transfer data from one ES cluster to another with document version, right now it only transfers data without a version of documents.

It would be nice if the library will allow transferring not only data but versions of each and every document.

**Comment by ferronrsmith** [comment]
Typical people who use ES, they don't store multiple versions and if versions are managed it's either 

1. back-end middleware logic to handle versions
1. an external versioning system.

This isn't the target audience `elasticsearch-dump` caters to. It's simple dumped of data from 1 source to the next. If you can access the data via a scroll/search endpoint, then it can be exported.

Otherwise it's not supported and likely will never be.
