### ISSUE TITLE
Detecting elasticsearch input/output conflicts with windows paths

### ISSUE THREAD

**Issue by gshively11** [taskrabbit/elasticsearch-dump#73]
These two lines cause issues when running on Windows:

https://github.com/taskrabbit/elasticsearch-dump/blob/ffed53f7e0fd7c67b30a6a65cfdf989a04d7f4db/elasticdump.js#L28
https://github.com/taskrabbit/elasticsearch-dump/blob/ffed53f7e0fd7c67b30a6a65cfdf989a04d7f4db/elasticdump.js#L42

Code is looking for ':' to determine whether or not an input/output is an elasticsearch url, however, Windows file paths contain ':' (e.g. C:\fTemp).

Discovered in this issue: https://github.com/godaddy/kibana4-backup/issues/4

(btw, great tool!)

**Comment by evantahler** [comment]
Oh windows... avoiding the conventions of every other OS...  

Can you try the tool without drive directive?  I don't have access to a windows machine, is there any other way to reference a drive-specific path without using a ":"?  perhaps \\\ or something?

If not (because I can't test it), I guess we need a new pull request to change that ":" to detecting a port of HTTP/(S) in the URL. 

care to write it up?

**Comment by gshively11** [comment]
I don't think you can get around specifying the drive (I'm not on Windows either, so I can't easily test it).  I'll get around to writing a PR at some point, maybe this weekend.  Shouldn't be too hard to detect a url using something other than :.

**Comment by evantahler** [comment]
Bump! Any progress?

**Comment by gshively11** [comment]
Haven't had a chance to work on it yet.  I'll try to get to it today, no promises though.

**Comment by gshively11** [comment]
Fixed in https://github.com/taskrabbit/elasticsearch-dump/pull/74, thanks for the merge!
